### ISSUE TITLE
No output results upon running executable

### ISSUE THREAD

**Issue by nadropper** [arcticlimer/djanho#6]
Hello, there. First, I'd like to thank you for this idea, it's a pretty cool project.

Sadly, I haven't been able to make a good use of it since it's not producing any results for me.

I cloned the repo, ran `cargo build -r` — which was successful. Then, I ran the sample usage command but I got no response from running that at all. I know it got built correctly because when I check the version it shows me `my app 0.1`. Am I missing something here? Or maybe I'm just doing something wrong?

By the way, I'm using a MacBook Pro with an Apple M1 chip running macOS Ventura 13.4.

<img width="1445" alt="Screenshot 2023-06-08 at 10 27 54 AM" src="https://github.com/viniciusmuller/djanho/assets/49292621/d3522994-1dec-4dc0-8256-6a10174e6ac4">

**Comment by viniciusmuller** [comment]
Hey @tminuswhat! It's been a while since I made this project, but IIRC djanho does not output the result, it writes it to a file.

You can see it here:
https://github.com/viniciusmuller/djanho/blob/c97cd4078bdd8e2de2e2437535e56ea36d28a550/src/main.rs#LL24C63-L24C63

There should be a `generated.lua` or `generated.vim` file in your directory, since that's the default filename it uses, you can also specify the `--output` option to specify the output path/filename.

Feel free to create a pull request adding an informative success message such as "result written to {output_path}!"

**Comment by tminuswhat** [comment]
Thanks! Yes, it did generate the files successfully. For some reason my terminal does not list them when running `ls` (I saw them in Finder). Anyway, I'll submit a PR for the app to provide feedback upon successful execution.

**Comment by nadropper** [comment]
Thanks! Yes, it did generate the files successfully. For some reason my terminal does not list them when running `ls` (I saw them in Finder). Anyway, I'll submit a PR for the app to provide feedback upon successful execution.
